# Generated by Django 4.0.2 on 2022-02-15 18:53

import base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('featured_photo', models.ImageField(max_length=200, upload_to=base.models.project_directory_path)),
                ('alt', models.CharField(blank=True, help_text='Fotoğraf için alt metin.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(max_length=200, upload_to=base.models.portfolio_directory_path)),
                ('alt', models.CharField(blank=True, help_text='Fotoğraf için alt metin.', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
        ),
    ]
