# Generated by Django 4.0.2 on 2022-03-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projectportfolio_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectportfolio',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
