# Generated by Django 4.0.2 on 2022-03-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_projectportfolio_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectportfolio',
            options={'ordering': ('index',)},
        ),
    ]
