# Generated by Django 4.0.2 on 2025-09-26 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_spamfilter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpamFilter',
        ),
    ]
