# Generated by Django 6.0.6 on 2026-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_project_draft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
